spring:
  data:
    mongodb:
      uri: mongodb+srv://vaibhavsingh:1234abcd@cluster0.x2hwkl9.mongodb.net/cloudmall?retryWrites=true&w=majority&appName=Cluster0
      database: cloudmall
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    com.mongodb: DEBUG
